# Transcribed from Delta Process Control Instruments flyer. (code, img, name, cat, specs)
D=[]
def a(code,img,name,cat,specs,desc=None): D.append(dict(code=code,img=img,name=name,cat=cat,specs=specs,desc=desc))
PG='pressure-gauges'
a('UP','up','Steel Case Pressure Gauge — Black Powder Coated',PG,[['Nominal size','40 / 50 / 63 / 80 / 100 / 150 / 250 mm'],['Wetted parts','Copper alloy'],['Accuracy','± 1.6% & ± 2.5% F.S.'],['Range','Up to 1000 bar']])
a('BI','bi','SS Case Brass Pressure Gauge',PG,[['Nominal size','50 / 63 / 100 mm'],['Wetted parts','Copper alloy'],['Accuracy','± 1.6% F.S. (63 & 100 mm); ± 2.5% F.S. (50 mm)'],['Range','-760 mmHg; 0 to 700 kg/cm²; -1 to 21 kg/cm²']])
a('CS','cs','All SS Capsule Type Pressure Gauge',PG,[['Nominal size','63 / 100 / 125 / 150 mm'],['Capsule','AISI SS 316'],['Accuracy','± 1.6% F.S.'],['Range','250 to 6000 mmWC']])
a('SP','sp','SS Compact Case Pressure Gauge',PG,[['Nominal size','63 / 100 mm'],['Wetted parts','AISI SS 316'],['Accuracy','± 1.6% F.S.'],['Range','Up to 400 bar'],['Execution','Dry / liquid filled']])
a('BW','bw','All SS Solid Front Pressure Gauge',PG,[['Nominal size','100 / 150 mm'],['Wetted parts','AISI SS 316L'],['Accuracy','± 1.0% F.S.'],['Range','Up to 1600 bar'],['Execution','Dry / liquid filled']])
a('DG','dg','Draft Gauge',PG,[['Nominal size','150 × 78 / 200 × 180 mm'],['Wetted parts','Copper alloy'],['Accuracy','± 2.5% F.S.'],['Range','50 to 6000 mmWC']])
a('AP','ap','Ammonia Pressure Gauge — Bourdon Type',PG,[['Nominal size','100 mm'],['Wetted parts','AISI SS 316'],['Accuracy','± 1.6% F.S.'],['Range','-1 kg/cm² to 25 kg/cm²']])
a('IP','ip','All SS Industrial Pressure Gauge',PG,[['Nominal size','100 / 125 / 150 / 200 / 250 mm'],['Wetted parts','AISI SS 316L'],['Accuracy','± 1.0% F.S.'],['Range','Up to 1600 bar'],['Execution','Dry / liquid filled']])
a('EP','ep','All SS Economical Pressure Gauge — Compact Case',PG,[['Nominal size','100 mm'],['Wetted parts','AISI SS 316L'],['Accuracy','± 1.6% F.S.'],['Range','Up to 400 bar'],['Execution','Dry / liquid filled']])
a('EA','ea','All SS Pressure Gauge — External Zero Adjustment',PG,[['Nominal size','100 mm'],['Wetted parts','AISI SS 316L'],['Accuracy','± 1% F.S.'],['Range','Up to 400 bar'],['Execution','Dry / liquid filled']])
a('MR','mr','Maximum Reading Pressure Gauge',PG,[['Nominal size','100 / 150 / 200 / 250 mm'],['Wetted parts','AISI SS 316'],['Accuracy','± 1% F.S.'],['Range','Up to 1600 bar'],['Execution','Dry / liquid filled']])
a('MG','mg-test','SS Case Test Gauge',PG,[['Nominal size','150 / 200 / 250 mm'],['Accuracy','± 0.25% F.S.'],['Range','Up to 1000 bar']])
a('IE','ie','Electric Contact Type Pressure Gauge',PG,[['Nominal size','100 / 150 mm'],['Wetted parts','AISI SS 316L'],['Accuracy','± 1.0% F.S.'],['Range','Up to 1600 bar']])
a('TC','tc-sanitary','All SS Sanitary Pressure Gauge',PG,[['Nominal size','50 / 63 / 100 mm'],['Diaphragm','AISI SS 316L'],['Accuracy','± 1.6% F.S.'],['Range','Up to 40 bar'],['Execution','Dry / liquid filled']])
a('DC','dc-gauge','All SS Schaffer High Pressure Gauge — Diaphragm Type',PG,[['Nominal size','100 / 150 mm'],['Accuracy','± 1.6% F.S.'],['Range','250 to 6000 mmWC'],['Connection','Screwed / flanged'],['Diaphragm','AISI SS 316L']])
a('SF','sf-gauge','All SS Schaffer Low Pressure Gauge — Diaphragm Type',PG,[['Nominal size','100 / 150 mm'],['Accuracy','± 1.6% F.S.'],['Range','250 to 6000 mmWC'],['Connection','Screwed / flanged'],['Diaphragm','AISI SS 316L']])
a('HG','hg','All SS Homogenizer Gauge — Diaphragm Type',PG,[['Nominal size','100 / 150 mm'],['Diaphragm','AISI SS 316L'],['Accuracy','± 1.6% F.S.'],['Range','Up to 1600 bar'],['Execution','Dry / liquid filled']])
a('DP','dp','Differential Pressure Gauge — Piston Operated',PG,[['Nominal size','63 / 100 / 150 mm'],['Wetted parts','AISI 304 SS, spring & screw with ceramic magnet'],['Accuracy','± 3% F.S.'],['Range','0 to 10.00 kg/cm²']])
a('DSD','dsd','Double Diaphragm Differential Pressure Gauge',PG,[['Nominal size','100 / 150 mm'],['Diaphragm','AISI SS 316L'],['Accuracy','± 1.6% F.S.'],['Range','Up to 25 bar']])
a('MG','mg-mud','Mud Gauge',PG,[['Nominal size','100 mm'],['Wetted parts','AISI SS 316'],['Accuracy','± 2.0% F.S.'],['Range','16 to 80 MPa']])
TG='temperature-gauges'
a('TG','tg','Fully SS Thermometer with Capillary',TG,[['Nominal size','100 / 125 / 150 / 200 / 250 mm'],['Wetted parts','AISI SS 316'],['Range','-80 to 650 °C'],['Type','Rigid stem / capillary'],['Filling fluid','Dry / liquid filled']])
a('TB','tb','Fully SS Bimetal Thermometer',TG,[['Nominal size','40 / 50 / 63 / 80 / 100 / 125 / 150 mm'],['Wetted parts','AISI SS 316'],['Range','-80 to 600 °C'],['Type','Bimetal']])
a('ET','et','Exhaust Thermometer with External Spring',TG,[['Nominal size','100 mm'],['Wetted parts','AISI 304 SS (bayonet type)'],['Accuracy','Class 1 as per EN 13190'],['Range','+50 to 650 °C']])
TW='thermowells'
a('FT','ft','Flanged Type Thermowell',TW,[['Model','EI1'],['Type','Fabricated from barstock'],['Connection','Flanged as per ANSI, JIS, DIN']])
a('SST','sst','Straight Screwed Type Thermowell',TW,[['Model','EI2'],['Type','Fabricated from barstock'],['Connection','Screwed'],['Construction','Straight']])
a('FTT','ftt','Flanged Tapered Type Thermowell',TW,[['Model','EI3'],['Type','Fabricated from barstock'],['Connection','Flanged'],['Construction','Tapered']])
a('TST','tst','Tapered Screwed Type Thermowell',TW,[['Type','Fabricated from barstock'],['Connection','Screwed'],['Construction','Tapered fully']])
DS='diaphragm-seals'
a('SC','sc','Diaphragm Seal — Sanitary Clamp Type',DS,[['Range','-1 to 40 bar'],['Connection','Sanitary seal'],['Wetted parts','AISI SS 316L']])
a('DIS','dis','Diaphragm Seal — "I" Section Type',DS,[['Flange as per','ANSI, ASA, DIN, JIS'],['Range','-1 to 400 bar'],['Wetted parts','AISI SS 316, SS 316L, Titanium, Hastelloy']])
a('DFF','dff','Diaphragm Seal — Direct Flanged Flush Type',DS,[['Flange as per','ANSI, ASA, DIN, JIS'],['Range','-1 to 250 bar'],['Wetted parts','AISI SS 316, SS 316L, Titanium, Hastelloy']])
a('DFI','dfi','Diaphragm Seal — Direct Flanged Insert Type',DS,[['Flange as per','ANSI, ASA, DIN, JIS'],['Range','-1 to 250 bar'],['Wetted parts','AISI SS 316, SS 316L, Titanium, Hastelloy']])
a('EN','en','Diaphragm Seal — Extended Neck Type',DS,[['Flange as per','ANSI, ASA, DIN, JIS'],['Range','-1 to 250 bar'],['Wetted parts','AISI SS 316']])
a('WT','wt','Diaphragm Seal — Wafer Type',DS,[['Flange as per','ANSI, ASA, DIN, JIS'],['Range','1 to 160 bar'],['Wetted parts','AISI SS 316']])
a('FR','fr-seal','Diaphragm Seal — Floating Ring Type',DS,[['Application','Pulp'],['Range','1 to 40 bar'],['Wetted parts','AISI SS 316, SS 316L']])
a('SRC','src','Diaphragm Seal — Slip Ring Coupled Type',DS,[['Range','-1 to 400 bar'],['Connection','Screwed'],['Wetted parts','AISI SS 316, SS 316L, Monel, Titanium']])
a('DC','dc-seal','Diaphragm Seal — Direct Coupled Type',DS,[['Range','-1 to 400 bar'],['Connection','Screwed'],['Wetted parts','AISI SS 316, SS 316L']])
a('CD','cd','Diaphragm Seal — Compact Design',DS,[['Range','Up to 21 bar'],['Connection','Screwed'],['Wetted parts','AISI SS 316']])
a('F/S','fs','Diaphragm Seal — Floating Type / Sanitary Type',DS,[['Range','Up to 40 bar'],['Connection','SMS / DIN / RJT / IDF'],['Wetted parts','AISI SS 316, SS 316L']])
a('SF','sf-seal','Diaphragm Seal — Screwed Flush Type',DS,[['Range','Up to 600 bar'],['Connection','Screwed'],['Wetted parts','AISI SS 316L, Hastelloy']])
a('HM','hm','Heavy Duty Mini Diaphragm Seal',DS,[['Wetted parts','AISI 316L SS'],['Range','-1 to 600 bar']])
NV='needle-valves'; MV='manifold-valves'; IA='instrumentation-accessories'
a('NV1','nv1','Needle Valve — NV1',NV,[['Material','AISI SS 316'],['Working pressure','400 bar'],['Working temperature','240 °C'],['Size','2"']])
a('NV3','nv3','Needle Valve — NV3',NV,[['Material','AISI SS 316 / SS 316L / Monel'],['Working pressure','400 bar'],['Working temperature','240 °C (max 550 °C)'],['Sizes','1/8" to 1"']])
a('2VM','2vm','Two Valve Manifold',MV,[['Material','AISI SS 316 / SS 316L / Monel'],['Working pressure','6000 psi'],['Working temperature','240 °C (max 550 °C)'],['Process side','1/2" NPT female'],['Instrument side','1/2" NPT female'],['Vent / test','1/4" NPT female']])
a('3VM','3vm','Three Valve Manifold',MV,[['Material','AISI SS 316 / SS 316L / Monel'],['Working pressure','6000 psi'],['Working temperature','240 °C (max 550 °C)'],['Process side','1/2" NPT female'],['Instrument side','1/2" NPT female'],['Vent / test','1/4" NPT female']])
a('5VM','5vm','Five Valve Manifold',MV,[['Material','AISI SS 316 / SS 316L / Monel'],['Working pressure','6000 psi'],['Working temperature','240 °C (max 550 °C)'],['Process side','1/2" NPT female'],['Instrument side','1/2" NPT female'],['Vent / test','1/4" NPT female']])
a('CT','ct','Cooling Tower (Gauge Accessory)',IA,[['Type','Perforated / fin type / capillary'],['MOC','AISI SS 316 / AISI SS 316L']])
a('GC','gc','Gauge Cock',IA,[['Material','AISI SS 316'],['Working temperature','Up to 180 °C'],['Gasket seal','PTFE'],['Pressure','100 kg/cm²']])
a('OP','op','Overload Protector',IA,[['Setting range','1.0 to 400 bar'],['Reset value','30% of set value'],['Max. working pressure','500 bar'],['Operating temperature','-20 °C to 200 °C'],['Material','AISI SS 316 / SS 316L / Monel']])
a('FR','fr-ring','Flushing Ring',IA,[['Flange size','2" to 5" as per ANSI B 16.5'],['Material','AISI 316 SS'],['Number of parts','Two'],['Port connection','1/4" NPT (F) with male plug'],['Sealing face','Raced face']])
a('SN','sn','Pulsation Dampener / Snubber',IA,[['Working pressure','Up to 400 kg/cm²'],['Working temperature','-20 °C to 200 °C'],['Material','AISI SS 316 / SS 316L / Monel']])
a('SY','sy','Syphon',IA,[['Type','Coil / pigtail / U type'],['MOC','AISI SS 316 / SS 316L / carbon steel'],['Pipe size','Schedule 40 / Schedule 80']])
RT='rtd-thermocouples'
a('RTD 3','rtd3','RTD Assembly with Fixed Threaded Extension',RT,[['Sensor','PT 100'],['Sheath material','AISI SS 316'],['Enclosure','Die cast aluminium'],['Configuration','3 wire system']])
a('RTD 4','rtd4','RTD Assembly with Adjustable Threaded Extension',RT,[['Sensor','PT 100'],['Sheath material','AISI SS 316'],['Enclosure','Die cast aluminium'],['Configuration','3 wire system']])
a('RTD 5','rtd5','RTD Insert with Threaded Pot & Lead Wires',RT,[['Sensor','PT 100'],['Sheath material','AISI SS 316'],['Configuration','3 wire system']])
a('RTD 8','rtd8','Bearing Temperature RTD',RT,[['Sensor','PT 100'],['Sheath material','AISI SS 316'],['Configuration','3 wire system']])
a('RTD 11','rtd11','RTD Assembly with Protecting Tube (Flanged Connection)',RT,[['Sensor','PT 100'],['Sheath material','AISI SS 316'],['Enclosure','Die cast aluminium'],['Configuration','3 wire system']])
a('RTD 12','rtd12','RTD Assembly with Adjustable Tri-Clamp Connection',RT,[['Sensor','PT 100'],['Sheath material','AISI SS 316'],['Enclosure','Die cast aluminium'],['Configuration','2–4 wire system']])
a('TC 1','tc1','Thermocouple Assembly with Adjustable Threaded Connection',RT,[['Type','Chromel-Alumel'],['Sheath material','AISI SS 316'],['Enclosure','Die cast aluminium'],['No. of elements','Simplex']])
a('TC 2','tc2','Thermocouple Assembly with Protecting Tube (Flanged Connection)',RT,[['Type','Chromel-Alumel'],['Sheath material','AISI SS 316'],['Enclosure','Die cast aluminium'],['No. of elements','Simplex']])
a('TC 4','tc4','Thermocouple Insert with Transition Joint',RT,[['Type','Chromel-Alumel'],['Sheath material','AISI SS 316'],['No. of elements','Simplex']])
a('TC 5','tc5','Thermocouple Insert with Plug & Jack Connector',RT,[['Type','Chromel-Alumel'],['Sheath material','AISI SS 316'],['No. of elements','Simplex']])
a('','service','Diaphragm Seal Repair & Refurbishment Service','instrumentation-accessories',[['Services offered','Transmitter assembling with diaphragm seal; diaphragm seal refurbishment & calibration'],['Typical reasons','Bulging of diaphragm; diaphragm blown up; corrosion damage; dents in the diaphragm; customised requirements of customer/process'],['Facilities','Laser welding of diaphragms; helium leak testing; HART calibration & simulation of transmitter']],
  desc='Repair and refurbishment of diaphragm seals, including transmitter assembly with diaphragm seal, refurbishment and calibration.')
print(len(D))
